from __future__ import annotations

"""Experimental generator: route DLC weapon patches through the already packaged
BaseGame/BPRUE files instead of creating GameLite/DLCGameData/<Pack>/ outputs.

This intentionally tests whether the runtime prototype database accepts DLC SIDs
when their patches are parsed from the normal BaseGame / ModGameData roots.
"""

import generate_all_cfg as gen
from upgrade_build_model import UpgradeBuildModel
from upgrade_renderers import (
    render_consolidated_upgrade_prototypes,
    render_dlc_general_setup_patch,
    render_final_general_setup_patch,
    render_technician_patch,
)


def _join_cfg(*parts: str) -> str:
    return "\n\n".join(part.rstrip() for part in parts if part.strip()) + "\n"


def _combined_upgrade_model(base: UpgradeBuildModel, dlc_models: dict[str, UpgradeBuildModel]) -> UpgradeBuildModel:
    combined = UpgradeBuildModel()
    combined.extend(base.upgrades)
    for pack in sorted(dlc_models):
        combined.extend(dlc_models[pack].upgrades)
    combined.validate()
    return combined


def _remove_old_dlc_outputs(dlc_models: dict[str, UpgradeBuildModel]) -> None:
    """Remove only files generated by BPRUE so a local test cannot accidentally
    succeed because stale DLCGameData output was still present from a normal run.
    """
    relative_paths = (
        "UpgradePrototypes/UpgradePrototypes_patch_BPRUE.cfg",
        "WeaponData/WeaponGeneralSetupPrototypes/WeaponGeneralSetupPrototypes_patch_BPRUE.cfg",
        "ItemPrototypes/ItemPrototypes_patch_BPRUE.cfg",
    )
    for pack in dlc_models:
        pack_root = gen.DLC_OUTPUT_ROOT / pack
        for relative in relative_paths:
            path = pack_root / relative
            if path.exists():
                path.unlink()
                print(f"Removed experimental stale DLC output {path}")


def main() -> None:
    print("Building BPRUE DLC-via-BaseGame packaging experiment")

    model, configs = gen.build_model(apply_layout=False)
    dlc_models = gen.build_dlc_outputs(model, configs)
    gen.apply_layout_to_model(model)
    model.validate()

    attachments = {
        sid: gen.attachment_block(data)
        for sid, data in gen.CONVERSION_ATTACHMENTS.items()
    }

    # Upgrade definitions themselves are written into the normal BPRUE
    # ModGameData file, which ZoneKit demonstrably packages and activates.
    # Using one combined model also avoids duplicate template definitions.
    combined_upgrades = _combined_upgrade_model(model, dlc_models)
    upgrade_text = render_consolidated_upgrade_prototypes(combined_upgrades)

    # The actual DLC SID patches are deliberately appended to the same BaseGame
    # files that already carry the working Vanilla patches. No DLCGameData output
    # is created by this experimental generator.
    setup_parts = [render_final_general_setup_patch(model, attachments)]
    weapon_parts = [gen.render_weapon_sections_patch(model)]
    for pack, dlc_model in sorted(dlc_models.items()):
        dlc_upgrade_text = render_consolidated_upgrade_prototypes(dlc_model)
        dlc_setup_text = render_dlc_general_setup_patch(dlc_model, pack)
        dlc_weapon_text = gen.render_weapon_sections_patch(dlc_model, content_pack=pack)
        gen.validate_rendered_outputs(dlc_model, dlc_upgrade_text, dlc_setup_text)
        setup_parts.append(
            f"// BPRUE EXPERIMENT: {pack} patches routed through BaseGame parser\n"
            + dlc_setup_text
        )
        weapon_parts.append(
            f"// BPRUE EXPERIMENT: {pack} patches routed through BaseGame parser\n"
            + dlc_weapon_text
        )

    setup_text = _join_cfg(*setup_parts)
    weapon_text = _join_cfg(*weapon_parts)
    npc_text = render_technician_patch(combined_upgrades)

    gen.validate_rendered_outputs(model, upgrade_text, setup_text, npc_text)

    gen.write(gen.UPGRADES_PATH, upgrade_text)
    gen.write(gen.GENERAL_SETUP_PATH, setup_text)
    gen.write(gen.WEAPON_PATH, weapon_text)
    gen.write(gen.NPC_PATH, npc_text)
    gen.write(gen.VANILLA_COMPACTION_PATH, gen.render_vanilla_compaction_patch())

    gen.write(gen.ar.EFFECT_OUTPUT_PATH, gen.ar.render_effect_patch(configs["ar"]))
    gen.write(gen.smg.EFFECT_OUTPUT_PATH, gen.smg.render_effects())
    gen.write(gen.shotgun.EFFECT_OUTPUT, gen.shotgun.render_effects())
    gen.write(gen.pistol.EFFECT_OUTPUT, gen.pistol.render_effects())
    gen.write(gen.sniper.EFFECT_OUTPUT, gen.sniper.render_effects())
    gen.write(gen.MACHINE_GUN_EFFECT_PATH, gen.machine_gun.render_effects())
    gen.write(gen.SHARED_EFFECT_PATH, gen.render_shared_effects())

    _remove_old_dlc_outputs(dlc_models)

    print(
        "Experimental output complete: "
        f"{len(model.upgrades)} base/Unique + "
        f"{sum(len(m.upgrades) for m in dlc_models.values())} DLC upgrades routed "
        "through ModGameData/BaseGame files; no BPRUE DLCGameData files remain."
    )


if __name__ == "__main__":
    main()
