from __future__ import annotations

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
CONTENT_ROOT = PYTHON_ROOT.parent
CONFIG_PATH = SCRIPT_DIR / "ak74_upgrades.json"
OUTPUT_PATH = CONTENT_ROOT / "GameLite" / "GameData" / "UpgradePrototypes" / "UpgradePrototypes_patch_BPRUE.cfg"


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def render_string_array(name: str, values: list[str], indent: str = "   ") -> list[str]:
    if not values:
        return []
    lines = [f"{indent}{name} : struct.begin"]
    for index, value in enumerate(values):
        lines.append(f"{indent}   [{index}] = {value}")
    lines.append(f"{indent}struct.end")
    return lines


def render_upgrade(upgrade: dict, image_root: str) -> str:
    lines = [
        f"{upgrade['sid']} : struct.begin {{refkey=[0]}}",
        f"   SID = {upgrade['sid']}",
        f"   Text = {upgrade['text_sid']}",
        f"   Hint = {upgrade['hint_sid']}",
        f"   Image = Texture2D'{image_root}/{upgrade['image']}'",
        f"   Icon = {upgrade['icon']}",
        f"   BaseCost = {upgrade['base_cost']}",
        f"   HorizontalPosition = {upgrade['horizontal_position']}",
        f"   VerticalPosition = {upgrade['vertical_position']}",
        f"   UpgradeTargetPart = {upgrade['target_part']}",
    ]

    lines += render_string_array("EffectPrototypeSIDs", upgrade.get("effect_sids", []))
    lines += render_string_array("RequiredUpgradePrototypeSIDs", upgrade.get("required_upgrade_sids", []))

    if upgrade.get("connection_lines"):
        lines += render_string_array("ConnectionLines", upgrade["connection_lines"])

    lines.append("struct.end")
    return "\n".join(lines)


def main() -> None:
    config = load_config()
    weapon = config["weapon"]

    rendered = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Content/Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_upgrades.py",
        "// -----------------------------------------------------------------------------",
        "",
        "// Experimental AK-74 upgrades.",
        "// Reuses existing vanilla effects; no new EffectPrototype is required.",
        "// Tree placement/prerequisites are intentionally isolated for in-game testing.",
        "",
    ]

    for upgrade in config["upgrades"]:
        rendered.append(render_upgrade(upgrade, weapon["image_root"]))
        rendered.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(rendered), encoding="utf-8")
    print(f"Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
