from __future__ import annotations

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
CONTENT_ROOT = PYTHON_ROOT.parent
CONFIG_PATH = SCRIPT_DIR / "ak74_upgrades.json"
UPGRADE_OUTPUT_PATH = CONTENT_ROOT / "GameLite" / "GameData" / "UpgradePrototypes" / "UpgradePrototypes_patch_BPRUE.cfg"
WEAPON_OUTPUT_PATH = CONTENT_ROOT / "GameLite" / "GameData" / "WeaponData" / "WeaponGeneralSetupPrototypes" / "WeaponGeneralSetupPrototypes_patch_BPRUE.cfg"


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def render_string_array(name: str, values: list[str], indent: str = "   ") -> list[str]:
    if not values:
        return []
    lines = [f"{indent}{name} : struct.begin"]
    for index, value in enumerate(values):
        lines.append(f"{indent}   [{index}] = {value}")
    lines.append(f"{indent}struct.end")
    return lines


def render_upgrade(upgrade: dict, image_root: str) -> str:
    lines = [
        f"{upgrade['sid']} : struct.begin {{refkey=[0]}}",
        f"   SID = {upgrade['sid']}",
        f"   Text = {upgrade['text_sid']}",
        f"   Hint = {upgrade['hint_sid']}",
        f"   Image = Texture2D'{image_root}/{upgrade['image']}'",
        f"   Icon = {upgrade['icon']}",
        f"   BaseCost = {upgrade['base_cost']}",
        f"   HorizontalPosition = {upgrade['horizontal_position']}",
        f"   VerticalPosition = {upgrade['vertical_position']}",
        f"   UpgradeTargetPart = {upgrade['target_part']}",
    ]

    lines += render_string_array("EffectPrototypeSIDs", upgrade.get("effect_sids", []))
    lines += render_string_array("RequiredUpgradePrototypeSIDs", upgrade.get("required_upgrade_sids", []))

    if upgrade.get("connection_lines"):
        lines += render_string_array("ConnectionLines", upgrade["connection_lines"])

    lines.append("struct.end")
    return "\n".join(lines)


def render_weapon_patch(weapon: dict, upgrades: list[dict]) -> str:
    start_index = int(weapon["upgrade_list_start_index"])
    lines = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Content/Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_upgrades.py",
        "// -----------------------------------------------------------------------------",
        "",
        f"// Register BPRUE upgrades on {weapon['prototype_sid']}.",
        f"{weapon['prototype_sid']} : struct.begin {{bpatch}}",
        "   UpgradePrototypeSIDs : struct.begin {bpatch}",
    ]

    for offset, upgrade in enumerate(upgrades):
        lines.append(f"      [{start_index + offset}] = {upgrade['sid']}")

    lines += [
        "   struct.end",
        "struct.end",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    config = load_config()
    weapon = config["weapon"]
    upgrades = config["upgrades"]

    rendered_upgrades = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Content/Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_upgrades.py",
        "// -----------------------------------------------------------------------------",
        "",
        "// Experimental AKM-74S upgrades.",
        "// Reuses existing vanilla effects; no new EffectPrototype is required.",
        "",
    ]

    for upgrade in upgrades:
        rendered_upgrades.append(render_upgrade(upgrade, weapon["image_root"]))
        rendered_upgrades.append("")

    UPGRADE_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    UPGRADE_OUTPUT_PATH.write_text("\n".join(rendered_upgrades), encoding="utf-8")
    print(f"Generated {UPGRADE_OUTPUT_PATH}")

    WEAPON_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    WEAPON_OUTPUT_PATH.write_text(render_weapon_patch(weapon, upgrades), encoding="utf-8")
    print(f"Generated {WEAPON_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
