from __future__ import annotations

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
CONTENT_ROOT = PYTHON_ROOT.parent
CONFIG_PATH = SCRIPT_DIR / "ak74_upgrades.json"
NPC_OUTPUT_PATH = CONTENT_ROOT / "GameLite" / "GameData" / "NPCPrototypes" / "NPCPrototypes_patch_BPRUE.cfg"
TRADER_OUTPUT_PATH = (
    CONTENT_ROOT
    / "GameLite"
    / "GameData"
    / "ItemGeneratorPrototypes"
    / "DynamicItemGenerator"
    / "DynamicItemGenerator_patch_BPRUE.cfg"
)


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def render_npc_patch(technician: dict, upgrades: list[dict]) -> str:
    lines = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_test_support.py",
        "// -----------------------------------------------------------------------------",
        "",
        "// Make the experimental upgrades available to technicians.",
        f"{technician['prototype_sid']} : struct.begin {{bpatch}}",
        "   Upgrades : struct.begin {bpatch}",
    ]

    for upgrade in upgrades:
        lines += [
            f"      {upgrade['sid']} : struct.begin",
            f"         UpgradePrototypeSID = {upgrade['sid']}",
            "         Enabled = true",
            "      struct.end",
        ]

    lines += [
        "   struct.end",
        "struct.end",
        "",
        f"{technician['all_prototype_sid']} : struct.begin {{bpatch}}",
        "   Upgrades : struct.begin {bpatch}",
    ]

    for upgrade in upgrades:
        lines += [
            "      [*] : struct.begin",
            f"         UpgradePrototypeSID = {upgrade['sid']}",
            "         Enabled = true",
            "      struct.end",
        ]

    lines += [
        "   struct.end",
        "struct.end",
        "",
    ]
    return "\n".join(lines)


def render_trader_patch(test_trader: dict, weapon: dict) -> str:
    lines = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_test_support.py",
        "// -----------------------------------------------------------------------------",
        "",
        f"// Test-only stock entry: make {weapon['prototype_sid']} available at {test_trader['name']}.",
        f"{test_trader['generator_sid']} : struct.begin {{bpatch}}",
        f"   SID = {test_trader['generator_sid']}",
        "   ItemGenerator : struct.begin {bpatch}",
    ]

    start_index = int(test_trader["start_index"])
    for offset, rank in enumerate(test_trader["player_ranks"]):
        lines += [
            f"      [{start_index + offset}] : struct.begin",
            "         Category = EItemGenerationCategory::WeaponPrimary",
            f"         PlayerRank = ERank::{rank}",
            "         bAllowSameCategoryGeneration = true",
            "         PossibleItems : struct.begin",
            "            [0] : struct.begin",
            f"               ItemPrototypeSID = {weapon['prototype_sid']}",
            "               Chance = 1",
            "               MinCount = 1",
            "               MaxCount = 1",
            "            struct.end",
            "         struct.end",
            "      struct.end",
        ]

    lines += [
        "   struct.end",
        "struct.end",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    config = load_config()
    weapon = config["weapon"]
    technician = config["technician"]
    test_trader = config["test_trader"]
    upgrades = config["upgrades"]

    NPC_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    NPC_OUTPUT_PATH.write_text(render_npc_patch(technician, upgrades), encoding="utf-8")
    print(f"Generated {NPC_OUTPUT_PATH}")

    TRADER_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    TRADER_OUTPUT_PATH.write_text(render_trader_patch(test_trader, weapon), encoding="utf-8")
    print(f"Generated {TRADER_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
