from __future__ import annotations

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
CONTENT_ROOT = PYTHON_ROOT.parent
CONFIG_PATH = SCRIPT_DIR / "ak74_upgrades.json"
NPC_OUTPUT_PATH = CONTENT_ROOT / "GameLite" / "GameData" / "NPCPrototypes" / "NPCPrototypes_patch_BPRUE.cfg"


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def render_appended_upgrade_entries(upgrades: list[dict], indent: str = "      ") -> list[str]:
    lines: list[str] = []
    for upgrade in upgrades:
        lines += [
            f"{indent}[*] : struct.begin",
            f"{indent}   UpgradePrototypeSID = {upgrade['sid']}",
            f"{indent}   Enabled = true",
            f"{indent}struct.end",
        ]
    return lines


def render_technician(prototype_sid: str, upgrades: list[dict]) -> list[str]:
    lines = [
        f"{prototype_sid} : struct.begin {{bpatch}}",
        "   Upgrades : struct.begin {bpatch}",
    ]
    lines += render_appended_upgrade_entries(upgrades)
    lines += [
        "   struct.end",
        "struct.end",
        "",
    ]
    return lines


def render_npc_patch(technician: dict, upgrades: list[dict]) -> str:
    lines = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_test_support.py",
        "// -----------------------------------------------------------------------------",
        "",
        "// TEST SETUP: append all experimental AK upgrades to every vanilla technician",
        "// prototype found in NPCPrototypes.cfg. Technician restrictions can be refined",
        "// later once the upgrade pipeline is verified end-to-end.",
        "",
    ]

    prototype_sids = [
        technician["prototype_sid"],
        technician["all_prototype_sid"],
        *technician.get("concrete_prototype_sids", []),
    ]

    seen: set[str] = set()
    for prototype_sid in prototype_sids:
        if prototype_sid in seen:
            continue
        seen.add(prototype_sid)
        lines += render_technician(prototype_sid, upgrades)

    return "\n".join(lines)


def main() -> None:
    config = load_config()
    technician = config["technician"]
    upgrades = config["upgrades"]

    NPC_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    NPC_OUTPUT_PATH.write_text(render_npc_patch(technician, upgrades), encoding="utf-8")
    print(f"Generated {NPC_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
