from __future__ import annotations

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
CONTENT_ROOT = PYTHON_ROOT.parent
CONFIG_PATH = SCRIPT_DIR / "ak74_upgrades.json"
UPGRADE_OUTPUT_PATH = CONTENT_ROOT / "GameLite" / "GameData" / "UpgradePrototypes" / "UpgradePrototypes_patch_BPRUE.cfg"
WEAPON_OUTPUT_PATH = CONTENT_ROOT / "GameLite" / "GameData" / "WeaponData" / "WeaponGeneralSetupPrototypes" / "WeaponGeneralSetupPrototypes_patch_BPRUE.cfg"
NPC_OUTPUT_PATH = CONTENT_ROOT / "GameLite" / "GameData" / "NPCPrototypes" / "NPCPrototypes_patch_BPRUE.cfg"


def load_config() -> dict:
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def render_string_array(name: str, values: list[str], indent: str = "   ", bpatch: bool = False) -> list[str]:
    if not values:
        return []
    patch_suffix = " {bpatch}" if bpatch else ""
    lines = [f"{indent}{name} : struct.begin{patch_suffix}"]
    for index, value in enumerate(values):
        lines.append(f"{indent}   [{index}] = {value}")
    lines.append(f"{indent}struct.end")
    return lines


def render_upgrade(upgrade: dict, image_root: str) -> str:
    lines = [
        f"{upgrade['sid']} : struct.begin {{refkey={upgrade['refkey']};bpatch}}",
        f"   SID = {upgrade['sid']}",
        f"   Text = {upgrade['text_sid']}",
        f"   Hint = {upgrade['hint_sid']}",
        f"   Image = Texture2D'{image_root}/{upgrade['image']}'",
        f"   Icon = {upgrade['icon']}",
        f"   BaseCost = {upgrade['base_cost']}",
        f"   HorizontalPosition = {upgrade['horizontal_position']}",
        f"   VerticalPosition = {upgrade['vertical_position']}",
        f"   UpgradeTargetPart = {upgrade['target_part']}",
    ]

    lines += render_string_array("EffectPrototypeSIDs", upgrade.get("effect_sids", []), bpatch=True)
    lines += render_string_array("RequiredUpgradePrototypeSIDs", upgrade.get("required_upgrade_sids", []))
    lines += render_string_array("ConnectionLines", upgrade.get("connection_lines", []))

    lines.append("struct.end")
    return "\n".join(lines)


def render_weapon_patch(weapon: dict, upgrades: list[dict]) -> str:
    lines = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_upgrades.py",
        "// -----------------------------------------------------------------------------",
        "",
        f"// Register experimental upgrade nodes on {weapon['prototype_sid']}.",
        f"{weapon['prototype_sid']} : struct.begin {{bpatch}}",
        "   UpgradePrototypeSIDs : struct.begin {bpatch}",
    ]

    for upgrade in upgrades:
        lines.append(f"      {upgrade['sid']} = {upgrade['sid']}")

    lines += [
        "   struct.end",
        "struct.end",
        "",
    ]
    return "\n".join(lines)


def render_npc_patch(technician: dict, upgrades: list[dict]) -> str:
    lines = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_upgrades.py",
        "// -----------------------------------------------------------------------------",
        "",
        "// Make the experimental upgrades available to technicians.",
        f"{technician['prototype_sid']} : struct.begin {{bpatch}}",
        "   Upgrades : struct.begin {bpatch}",
    ]

    for upgrade in upgrades:
        lines += [
            f"      {upgrade['sid']} : struct.begin",
            f"         UpgradePrototypeSID = {upgrade['sid']}",
            "         Enabled = true",
            "      struct.end",
        ]

    lines += [
        "   struct.end",
        "struct.end",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    config = load_config()
    weapon = config["weapon"]
    technician = config["technician"]
    upgrades = config["upgrades"]

    rendered_upgrades = [
        "// -----------------------------------------------------------------------------",
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND",
        "//",
        "// Source: Python/CFGGenerators/Weapons/ak74_upgrades.json",
        "// Generated by: generate_ak74_upgrades.py",
        "// -----------------------------------------------------------------------------",
        "",
        "// AKM-74S technician-tree experiment.",
        "// Fire-rate, reload-speed and caliber-conversion test nodes.",
        "",
    ]

    for upgrade in upgrades:
        rendered_upgrades.append(render_upgrade(upgrade, weapon["image_root"]))
        rendered_upgrades.append("")

    UPGRADE_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    UPGRADE_OUTPUT_PATH.write_text("\n".join(rendered_upgrades), encoding="utf-8")
    print(f"Generated {UPGRADE_OUTPUT_PATH}")

    WEAPON_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    WEAPON_OUTPUT_PATH.write_text(render_weapon_patch(weapon, upgrades), encoding="utf-8")
    print(f"Generated {WEAPON_OUTPUT_PATH}")

    NPC_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    NPC_OUTPUT_PATH.write_text(render_npc_patch(technician, upgrades), encoding="utf-8")
    print(f"Generated {NPC_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
