from __future__ import annotations

from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
CONTENT_ROOT = PYTHON_ROOT.parent
UPGRADE_DIR = CONTENT_ROOT / "GameLite" / "ModGameData" / "BPRUpgradesExpanded" / "UpgradePrototypes"
TARGET = UPGRADE_DIR / "BPRUE_UpgradePrototypes.cfg"

# Generator-specific files are temporary build products. The assault-rifle
# generator already owns BPRUE_UpgradePrototypes.cfg, so keep that as the base
# and append every generated weapon class in a deterministic order.
GENERATED_SOURCES = [
    UPGRADE_DIR / "BPRUE_SMGUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_ShotgunUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_PistolUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_SniperUpgradePrototypes.cfg",
]

# The pistol-conversion prototypes predate the class generators and currently
# live as a checked-in standalone source on main. They are not regenerated by
# generate_all_cfg.py, so the merger must not require a local split file that a
# previous successful run may already have removed. Until these definitions are
# moved into a generator, keep them in the final consolidated file by extracting
# them from the existing target when present. A clean checkout of this branch
# already contains them in BPRUE_UpgradePrototypes.cfg after consolidation.
CONVERSION_MARKER = "BPRUE_SMGConversionUpgradeTemplate"


def extract_conversion_section(text: str) -> str:
    marker_pos = text.find(CONVERSION_MARKER + " : struct.begin")
    if marker_pos < 0:
        return ""

    # Conversion section is appended as one contiguous source section. Preserve
    # it up to the next generated class header if present.
    end = len(text)
    for marker in (
        "// -----------------------------------------------------------------------------\n// BPRUE SHOTGUN",
        "// -----------------------------------------------------------------------------\n// BPRUE PISTOL",
        "// -----------------------------------------------------------------------------\n// BPRUE SNIPER",
    ):
        pos = text.find(marker, marker_pos + 1)
        if 0 <= pos < end:
            end = pos
    return text[marker_pos:end].strip()


def main() -> None:
    if not TARGET.exists():
        raise FileNotFoundError(
            f"Missing base upgrade file: {TARGET}. Run the assault-rifle generator before this merger."
        )

    base_content = TARGET.read_text(encoding="utf-8").rstrip()
    sections = [base_content]

    # Backward-compatible migration path: if the old standalone conversion file
    # still exists (e.g. first run after updating the branch), consume it once.
    conversion_path = UPGRADE_DIR / "BPRUE_SMGConversionUpgradePrototypes.cfg"
    conversion_content = ""
    if conversion_path.exists():
        conversion_content = conversion_path.read_text(encoding="utf-8").strip()
    else:
        conversion_content = extract_conversion_section(base_content)
    if conversion_content and CONVERSION_MARKER not in base_content:
        sections.append(conversion_content)

    for source in GENERATED_SOURCES:
        if not source.exists():
            raise FileNotFoundError(
                f"Missing generated upgrade file: {source}. Run all weapon generators before this merger."
            )
        content = source.read_text(encoding="utf-8").strip()
        if content:
            sections.append(content)

    header = (
        "// -----------------------------------------------------------------------------\n"
        "// CONSOLIDATED BPRUE UPGRADE PROTOTYPES\n"
        "// Generated by the class-specific weapon generators and merged by\n"
        "// merge_upgrade_prototypes.py. Do not edit generated sections by hand.\n"
        "// -----------------------------------------------------------------------------\n\n"
    )

    TARGET.write_text(header + "\n\n".join(sections) + "\n", encoding="utf-8")

    for source in GENERATED_SOURCES:
        source.unlink(missing_ok=True)
    conversion_path.unlink(missing_ok=True)

    print(f"Consolidated upgrade prototypes into {TARGET}")
    print("Removed split SMG, shotgun, pistol and sniper upgrade prototype files.")


if __name__ == "__main__":
    main()
