from __future__ import annotations

from pathlib import Path

from apply_module_layout import class_columns, file_class_hint, load_configs, patch_block

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
CONTENT_ROOT = PYTHON_ROOT.parent
UPGRADE_DIR = CONTENT_ROOT / "GameLite" / "ModGameData" / "BPRUpgradesExpanded" / "UpgradePrototypes"
TARGET = UPGRADE_DIR / "BPRUE_UpgradePrototypes.cfg"

# Generator-specific files are temporary build products. The assault-rifle
# generator already owns BPRUE_UpgradePrototypes.cfg, so keep that as the base
# and append every generated weapon class in a deterministic order.
GENERATED_SOURCES = [
    UPGRADE_DIR / "BPRUE_SMGUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_ShotgunUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_PistolUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_SniperUpgradePrototypes.cfg",
]


def apply_layout(content: str, path: Path, configs: dict, columns: dict) -> str:
    """Apply module columns while content is already in memory for consolidation.

    This deliberately replaces the old pipeline step that wrote each generated
    class CFG, reopened it in apply_module_layout.py, rewrote it, and then opened
    it a third time here just to merge it.
    """
    lines = content.splitlines()
    out: list[str] = []
    i = 0
    hint = file_class_hint(path)

    while i < len(lines):
        line = lines[i]
        if not line.startswith((" ", "\t")) and ": struct.begin" in line:
            block = [line]
            depth = 1
            i += 1
            while i < len(lines) and depth:
                block.append(lines[i])
                stripped = lines[i].strip()
                if "struct.begin" in stripped:
                    depth += 1
                if stripped == "struct.end":
                    depth -= 1
                i += 1
            block, _ = patch_block(block, hint, configs, columns)
            out.extend(block)
            continue
        out.append(line)
        i += 1

    return "\n".join(out)


def main() -> None:
    if not TARGET.exists():
        raise FileNotFoundError(
            f"Missing base upgrade file: {TARGET}. Run the assault-rifle generator before this merger."
        )

    configs = load_configs()
    columns = class_columns(configs)

    # Layout is applied here, immediately before the final file is assembled.
    # No generated class CFG is rewritten as an intermediate processing step.
    sections = [apply_layout(TARGET.read_text(encoding="utf-8").rstrip(), TARGET, configs, columns)]

    for source in GENERATED_SOURCES:
        if not source.exists():
            raise FileNotFoundError(
                f"Missing generated upgrade file: {source}. Run all weapon generators before this merger."
            )
        content = source.read_text(encoding="utf-8").strip()
        if content:
            sections.append(apply_layout(content, source, configs, columns))

    header = (
        "// -----------------------------------------------------------------------------\n"
        "// CONSOLIDATED BPRUE UPGRADE PROTOTYPES\n"
        "// Generated by the class-specific weapon generators and finalized by\n"
        "// merge_upgrade_prototypes.py (including module layout).\n"
        "// -----------------------------------------------------------------------------\n\n"
    )

    TARGET.write_text(header + "\n\n".join(sections) + "\n", encoding="utf-8")

    for source in GENERATED_SOURCES:
        source.unlink(missing_ok=True)

    # Clean up the obsolete pre-generator split file if it is still present in
    # an older working tree. It is no longer a source of truth.
    (UPGRADE_DIR / "BPRUE_SMGConversionUpgradePrototypes.cfg").unlink(missing_ok=True)

    print(f"Applied module layout and consolidated upgrade prototypes into {TARGET}")
    print("Removed split SMG, shotgun, pistol and sniper upgrade prototype files.")


if __name__ == "__main__":
    main()
