from __future__ import annotations

from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PYTHON_ROOT = SCRIPT_DIR.parents[1]
CONTENT_ROOT = PYTHON_ROOT.parent
UPGRADE_DIR = CONTENT_ROOT / "GameLite" / "ModGameData" / "BPRUpgradesExpanded" / "UpgradePrototypes"
TARGET = UPGRADE_DIR / "BPRUE_UpgradePrototypes.cfg"

# Generator-specific files are temporary build products. The assault-rifle
# generator already owns BPRUE_UpgradePrototypes.cfg, so keep that as the base
# and append every other weapon class plus the SMG conversion upgrades in a
# deterministic order.
SOURCES = [
    UPGRADE_DIR / "BPRUE_SMGUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_SMGConversionUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_ShotgunUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_PistolUpgradePrototypes.cfg",
    UPGRADE_DIR / "BPRUE_SniperUpgradePrototypes.cfg",
]


def main() -> None:
    if not TARGET.exists():
        raise FileNotFoundError(
            f"Missing base upgrade file: {TARGET}. Run the weapon generators before this merger."
        )

    sections = [TARGET.read_text(encoding="utf-8").rstrip()]

    for source in SOURCES:
        if not source.exists():
            raise FileNotFoundError(
                f"Missing generated upgrade file: {source}. Run all weapon generators before this merger."
            )
        content = source.read_text(encoding="utf-8").strip()
        if content:
            sections.append(content)

    header = (
        "// -----------------------------------------------------------------------------\n"
        "// CONSOLIDATED BPRUE UPGRADE PROTOTYPES\n"
        "// Generated by the class-specific weapon generators and merged by\n"
        "// merge_upgrade_prototypes.py. Do not edit generated sections by hand.\n"
        "// -----------------------------------------------------------------------------\n\n"
    )

    TARGET.write_text(header + "\n\n".join(sections) + "\n", encoding="utf-8")

    for source in SOURCES:
        source.unlink(missing_ok=True)

    print(f"Consolidated upgrade prototypes into {TARGET}")
    print("Removed split SMG, SMG conversion, shotgun, pistol and sniper upgrade prototype files.")


if __name__ == "__main__":
    main()
